services:
  - type: web
    name: tg-forward-bot
    env: docker
    autoDeploy: true
    healthCheckPath: /healthz
    disks:
      - name: data
        mountPath: /data
        sizeGB: 1
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_SECRET_TOKEN
        generateValue: true
      - key: APP_BASE_URL
        sync: false
      - key: PAIRS_FILE
        value: /data/pairs.json
